name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0 # Full git history is needed for proper modification datetimes for jekyll pages/posts

      - name: Setup NodeJS
        uses: actions/setup-node@v4.4.0
        with:
          node-version: latest

      - name: Deploy to github pages (branch)
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: pages
          folder: ./web
          commit-message: "deploy: website [ci skip]"
          single-commit: true
